ehl now highlights errors/success/etc

diff --git a/bin/ehl b/bin/ehl
--- a/bin/ehl
+++ b/bin/ehl
@@ -3,7 +3,7 @@
 
 if [ ! $1 ]; then
         echo "Usage: $0 <command> <args...>"
-        echo "Error highlight: runs command with red stderr"
+        echo "Error highlight: runs command with red stderr and otherwise coloured errors/warnings"
         exit 1
 fi
 
@@ -12,6 +12,15 @@ export PATH=.:$PATH
 
 set -o pipefail
 
-( "$@" 2>&1>&3 | sed $'s,.*,\e[31m&\e[m,'>&2 ) 3>&1 \
-        | sed $'s,.*,&,' # keeps stderr and stdout at roughly same flow rate so order is roughly preserved
+# OK, time for cryptic stupidity
+# * STDERR in red
+# * lines with 'error' in red
+# * lines with 'warning' in yellow
+# * lines with 'success' or likewise in green
+( "$@" 2>&1>&3 | sed -u $'s,.*,\e[31m&\e[m,'>&2 ) 3>&1 \
+	| sed -u $'s,.*error.*,\e[31m&\e[m,ig' \
+	| sed -u $'s,.*warning.*,\e[33m&\e[m,ig' \
+	| sed -ur $'s,.*(success|passed|complete).*,\e[32m&\e[m,ig'
 
+# using sed on stdout also keeps stderr and stdout at roughly same flow rate so
+# order is roughly preserved
