trap CTRL+C for tryforever

diff --git a/bin/tryforever b/bin/tryforever
--- a/bin/tryforever
+++ b/bin/tryforever
@@ -1,6 +1,8 @@
 #!/bin/bash
 
 
+trap exit SIGINT
+
 if [ ! $1 ]; then
 	echo "Usage: $0 <command> <args...>"
 	echo "Keep trying command until it succeeds. Useful for trainternets."
@@ -9,5 +11,5 @@ fi
 
 while sleep 1; do
 	"$@" && exit 0
-	echo -e "\e[31m$1 Failed, trying again...\e[0m"
+	echo -e "\033[31m$1 command failed, trying again...\033[0m"
 done
